site_name: Discordoo Guide
site_url: 'https://docs.discordoo.xyz'

plugins:
  - search
  - awesome-pages

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: ddoo-light
      toggle:
        icon: fontawesome/regular/moon
        name: Switch to dark mode
    - media: ""
      scheme: ddoo-oceanic
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: ddoo-dark
      toggle:
        icon: material/water
        name: Switch to oceanic mode
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.sections
#    - navigation.instant
    - navigation.sections
    - navigation.expand

extra_css:
  - stylesheets/colors.css
  - //cdnjs.cloudflare.com/ajax/libs/animsition/4.0.2/css/animsition.min.css
#  - stylesheets/m-pagetransition-styles.css
#  - //cdnjs.cloudflare.com/ajax/libs/highlight.js/11.0.1/styles/github.min.css

extra_javascript:
#  - //unpkg.com/kotlin-playground@1
  - //code.jquery.com/jquery-3.1.1.min.js
  - //cdnjs.cloudflare.com/ajax/libs/highlight.js/11.0.1/highlight.min.js
  - //cdnjs.cloudflare.com/ajax/libs/animsition/4.0.2/js/animsition.min.js
  - javascripts/highlight.js
  - javascripts/pagetransition.js

markdown_extensions:
  - pymdownx.tabbed
  - meta
  - attr_list
  - toc:
      permalink: '#'
      toc_depth: 3
