site_name: Discordoo Guide
site_url: 'https://docs.discordoo.xyz'

plugins:
  - search
  - awesome-pages

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: ddoo-light
      toggle:
        icon: fontawesome/regular/moon
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: ddoo-dark
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.sections
    - navigation.expand

extra_css:
  - stylesheets/colors.css

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.superfences
  - meta
  - attr_list
  - toc:
      permalink: '#'
