site_name: Discordoo Guide
site_url: https://docs.discordoo.xyz

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png

extra_css:
  - stylesheets/colors.css

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.superfences
